packages:
  - 'packages/**'
  - 'tooling/**'

catalogs:
  dev:
    '@pixpilot/dev-config': ^3.6.0
    '@types/node': ^22.18.10
    '@vitest/coverage-v8': ^3.2.4
    '@vitest/ui': ^3.2.4
    eslint: ^9.38.0
    glob: ^11.0.3
    prettier: ^3.6.2
    rollup: ^4.52.4
    typescript: ^5.9.3
    vitest: ^3.2.4
    "@types/bytes": "^3.1.5"
  prod:
    "@manypkg/get-packages": ^3.1.0
    "bytes": ^3.1.2